services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
  
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
  
#   mongodb:
#     image: mongo:7.0
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     volumes:
#       - mongodb_data:/data/db
  
#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express
#     ports:
#       - "8081:8081"
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: example
#       ME_CONFIG_MONGODB_SERVER: mongodb

# volumes:
#   mongodb_data:
#     driver: local